---
version: "3.8"
services:
  web-ui:
    image: nodejs:20.10-alpine3.19
    container_name: sprinkler-controller-web-ui
    ports:
      - "3000:3000"
    networks:
      - sprinkler_controller_network
    build:
      context: ./
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      controller-service:
        condition: started
      db:
        condition: service_healthy
    restart: unless-stopped

  controller-service:
    image: controller-service:1.0.0
    container_name: controller-service
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - sprinkler_controller_network
    volumes:
      - .env:/app/.env
      - ./controller/config.json:/app/data/config.json
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      db:
        condition: service_healthy

networks:
  sprinkler_controller_network:
    driver: "bridge"